name: ca_portal_2
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  device_info_plus: ^12.2.0
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  get: ^4.7.2
  bottom_bar: ^2.0.5
  percent_indicator: ^4.2.5
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/ca.png
    - assets/image/Trofeee.png
  fonts:
    - family: myfont
      fonts:
        - asset: assets/fonts/playfairfont.ttf
